language: go

go:
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test ./... -coverprofile=coverage.out && go tool cover -func=coverage.out